import math

print("abs(-5) = ", abs(-5))
print("pow(2, 3) = ", pow(2, 3))
print("round(3.14159, 2) = ", round(3.14159, 0))
print("max(1, 2, 3, 4, 5) = ", max(1, 2, 3, 4, 5))
print("min(1, 2, 3, 4, 5) = ", min(1, 2, 3, 4, 5))
print("math.sin(math.pi/2) = ", math.sin(math.pi/2))
print("math.cos(0) = ", math.cos(0))
print("math.tan(math.pi/4) = ", math.tan(math.pi/4))
print("math.sqrt(9) = ", math.sqrt(9))
print("math.factorial(5) = ", math.factorial(5))
print("math.log(10) = ", math.log(10))
print("math.log10(100) = ", math.log10(100))
print("math.exp(2) = ", math.exp(2))
print("math.ceil(4.7) = ", math.ceil(4.7))
print("math.floor(4.7) = ", math.floor(4.7))
print("math.pi = ", math.pi)
print("math.e = ", math.e)
print("math.tau = ", math.tau)
print("math.inf = ", math.inf)
print("math.nan = ", math.nan)